# More configs could be found at https://github.com/kelseyhightower/confd/blob/master/docs/configuration-guide.md
backend = "etcdv3"
confdir = "/etc/confd"
log-level = "debug"
nodes = [
  "http://10.140.0.3:2379",
  "http://10.140.0.4:2379",
  "http://10.140.0.7:2379",
]
watch = true
